version: "3.9"
services:
  auth_db:
    image: postgres
    container_name: auth_db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cd_auth
      - PGDATA=/var/lib/postgresql/auth_data
    volumes:
      - ./db/auth_data:/var/lib/postgresql/auth_data
    restart: always

  auth:
    container_name: auth
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    ports:
      - "9900:9900"
    depends_on:
      - auth_db

  desc_db:
    image: postgres
    container_name: desc_db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cd_desc
      - PGDATA=/var/lib/postgresql/desc_data
    volumes:
      - ./db/desc_data:/var/lib/postgresql/desc_data
    restart: always

  desc:
    container_name: desc
    build:
      context: ./services/desc
      dockerfile: Dockerfile
    ports:
      - "9902:9902"
    depends_on:
      - desc_db

  mock_db:
    image: postgres
    container_name: mock_db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mock
      - PGDATA=/var/lib/postgresql/mock_data
    volumes:
      - ./db/mock_data:/var/lib/postgresql/mock_data
    restart: always

  mock:
    container_name: mock
    build:
      context: ./services/mock
      dockerfile: Dockerfile
    ports:
      - "9912:9912"
    depends_on:
      - desc_db

  notification_db:
    image: postgres
    container_name: notification_db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cd_notification
      - PGDATA=/var/lib/postgresql/notification_data
    volumes:
      - ./db/notification_data:/var/lib/postgresql/notification_data
    restart: always

  notification:
    container_name: notification
    build:
      context: ./services/notification
      dockerfile: Dockerfile
    ports:
      - "9920:9920"
    depends_on:
      - notification_db

  site:
    container_name: site
    build:
      context: ./services/site
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - auth
      - desc
      - mock
      - notification